# When we run the make command, since we're not giving it a target, the first target is ran
# Aka, the only target that's in the file

# First example that doesn't recompile if any changes are made
#main:
# This is the first example
#	cc main.c -o testing

# Seocnd example that recompiles if changes are made
# Note : prerequisite is added

main: main.c
	cc main.c -o testing